### ISSUE TITLE
Turn on github pages

### ISSUE THREAD

**Issue by fritzm** [smonkewitz/scisql#23]
If github pages feature were enabled and configured to point to doc directory, up-to-date documentation would be automatically published at https://smonkewitz.github.io/scisql.

**Comment by smonkewitz** [comment]
I enabled pages, but as far as I can tell you can't configure it to point to an arbitrary subdirectory - just the project root or the `docs/` subdir.

**Comment by fritzm** [comment]
Oh, I had thought that was a general option, but looking at the docs again I guess just those two choices...  Oddly, though, the docs _do_ appear at https://smonkewitz.github.io/scisql/ now!

**Comment by smonkewitz** [comment]
That's because I moved the directory in `tweaks_fo_gh_pages` branch, and temporarily configured that as the pages branch. There's a few more things I'd like to do (e.g. move to markdown for the README/TODO files) before I send a PR your way though.

**Comment by smonkewitz** [comment]
https://github.com/smonkewitz/scisql/pull/24

**Comment by fritzm** [comment]
Nice.  Thanks!
