### ISSUE TITLE
not compatible with mariadb

### ISSUE THREAD

**Issue by wangd** [smonkewitz/scisql#3]
This isn't exactly a bug, but more of a feature request.

If possible, we'd like to make it possible to install into mariadb. Here are a few things.

--- copied from qserv-l:  https://listserv.slac.stanford.edu/cgi-bin/wa?A2=QSERV-L;1d9d000b.1402 ---
Osma Aidel, database expert at CC-IN2P3, find out some problems when 
installing SciSQL in MariaDB.

Here are some of them :

1. default plugin dir has been modified, so next option has to be added 
to configure : --mysql-plugins=/usr/local/mysql/lib/plugin

2. MariaDB version isn't recognize at configure time :
--
Checking for mysql plugins directory     : /usr/local/mysql/lib/plugin
Checking for mysql.h                     : yes
Checking MySQL version                   : Invalid MYSQL_SERVER_VERSION 
5.5.34-MariaDB
--

3. after having hacked 2, a problem occurs during install :
[qserv@clrlsstwn04 scisql-0.3.2]$ make install
Waf: Entering directory `/home/qserv/src/scisql-0.3.2/build'
...
Running testS2PtInBox.py                 : OK
Running testS2PtInCircle.py              : OK
Running testS2PtInEllipse.py             : OK
Running docs.py                          : FAIL [see 
/home/qserv/src/scisql-0.3.2/build/tools/docs.log]

9 tests passed, 1 failed, and 0 failed to run

docs.log contains next message :
ERROR 1148 (42000) at line 5: The used command is not allowed with this 
MariaDB version
Failed to run documentation example:

TRUNCATE TABLE Science_Ccd_Exposure_HtmId10;
LOAD DATA LOCAL INFILE '/tmp/scisql_demo_htmid10.tsv' INTO TABLE 
Science_Ccd_Exposure_HtmId10;

The problem is that "local-infile" isn't allowed by default, so mysql 
client has to be launched with next option :

mysql --local-infile=1 -u root -p

MariaDB [scisql_demo]> TRUNCATE TABLE Science_Ccd_Exposure_HtmId10;
Query OK, 0 rows affected (0.00 sec)

MariaDB [scisql_demo]> LOAD DATA LOCAL INFILE 
'/tmp/scisql_demo_htmid10.tsv' INTO TABLE Science_Ccd_Exposure_HtmId10;
Query OK, 123 rows affected (0.00 sec)
Records: 123  Deleted: 0  Skipped: 0  Warnings: 0
------------

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-02-27T21:51:15Z
 * owner: wangd
 * the launchpad url was https://bugs.launchpad.net/bugs/1285877

**Comment by smonkewitz** [comment]
I think this is was (mostly?) addressed by DM-4642 (358f947).

**Comment by fjammes** [comment]
Yes, I think DM-4642 solves issues listed above.
